export const FETCH_PROFILE = 'FETCH_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const LOADING_CUSTOMERS = 'LOADING_CUSTOMERS';
export const REFRESHING_CUSTOMERS = 'REFRESHING_CUSTOMERS';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const FETCH_MORE_CUSTOMERS = 'FETCH_MORE_CUSTOMERS';