export const LOADING_SERVICES = 'LOADING_SERVICES';
export const REFRESHING_SERVICES = 'REFRESHING_SERVICES';
export const FETCH_SERVICES = 'FETCH_SERVICES';
export const FETCH_MORE_SERVICES = 'FETCH_MORE_SERVICES';
export const SET_FILTERS = 'SET_FILTERS';
export const LOADING_PROFILE = 'LOADING_PROFILE';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';